In [1]:
import pymongo, os, re, glob
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from collections import OrderedDict, defaultdict
from sklearn.cluster import KMeans
from scipy.sparse import csr_matrix
from sklearn.decomposition import PCA
import nltk
from com.ibm.watson.datasource.clinicaltrials import ClinicalTrials, ClinicalStudy

/Users/singhv/Library/Python/2.7/lib/python/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')


In [2]:
DESKTOP = os.path.join(os.environ["HOME"], "Desktop")
DOCUMENTS = os.path.join(os.environ["HOME"], "Documents")

In [25]:
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5], [6]])
print array1
print array2
array3 = np.append(array1, array2, axis=1)
print array3

[[1 2]
 [3 4]]
[[5]
 [6]]
[[1 2 5]
 [3 4 6]]
